--- #YAML:1.0
name:               Browser-FingerPrint
version:            v0.1
abstract:           Web Browser Fingerprinting
author:
    - Rohan Almeida <rohan@almeida.in>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
